include:
  - local: .gitlab-ci-common.yml
stages:
  - build
build-nvidia-test-image:
  extends: .bluebuild-job-template
  stage: build
  script:
    - bluebuild build --verbose --compression-format zstd --push ./recipes/test-nvidia.yml
